mysql migration
bytedance/fedlearner pull request #335
Opened 2020-09-21 06:52 UTC by TelmaZzzz

2020-09-21 09:27 UTC, piiswrong commented on deploy/scripts/data_join/run_data_join_master.sh
> +    --mysql_addr=$MYSQL_ADDR \
这个name和addr有啥用，是不是可以删了

2020-09-21 10:05 UTC, marswong requested changes

2020-09-21 10:05 UTC, marswong commented on fedlearner/common/mysql_client.py
> +                                       use_mock_mysql)
apply `unix_socket` with env here

2020-09-21 10:05 UTC, marswong commented on fedlearner/common/mysql_client.py
> +        self._name = name
set `_unix_socket` here

2020-09-21 10:29 UTC, piiswrong commented on deploy/scripts/data_join/run_data_join_master.sh
> +    --mysql_password=$MYSQL_PASSWORD \
这个叫 
 DB_DATABASE: 'fedlearner',
  DB_USERNAME: 'fedlearner',
  DB_PASSWORD: 'fedlearner',

2020-09-21 10:30 UTC, piiswrong commented on deploy/scripts/data_join/run_data_join_master.sh
> +    --mysql_base_dir=$MYSQL_BASE_DIR \
MYSQL_BASE_DIR是干啥的

2020-09-21 10:32 UTC, piiswrong commented on fedlearner/data_join/common.py
> +    mysql_key = data_source_mysql_base_dir(data_source_name)
这些要不不要叫etcd/mysql改来改去，统一叫kvstore吧，具体用啥看情况

2020-09-21 11:08 UTC, TelmaZzzz commented on fedlearner/data_join/common.py
> +    mysql_key = data_source_mysql_base_dir(data_source_name)
👌

2020-09-21 11:09 UTC, TelmaZzzz commented on deploy/scripts/data_join/run_data_join_master.sh
> +    --mysql_base_dir=$MYSQL_BASE_DIR \
这个是来生成key的

2020-09-21 11:09 UTC, TelmaZzzz commented on deploy/scripts/data_join/run_data_join_master.sh
> +    --mysql_password=$MYSQL_PASSWORD \
嗯嗯 这个我改下

2020-09-28 08:17 UTC, piiswrong commented on deploy/scripts/data_join/run_data_join_master.sh
> +    --db_database=$DB_DATABASE \
kvstore_type='etcd'/'mysql'，默认用etcd（也可以默认用空，script里加入etcd默认值），用normalize_env_to_args
etcd_base_dir命令行不输入，代码里读环境变量，默认"fedlearner"
etcd_name考虑去掉。
DB_XXX类似etcd_base_dir。

2020-09-28 08:17 UTC, piiswrong commented on fedlearner/common/mock_mysql.py
> +class MockMySQL(object):
和mocketcd合并为mock kvstore

2020-09-28 08:20 UTC, piiswrong commented on fedlearner/data_join/cmd/data_join_master_service.py
> -    parser.add_argument('--use_mock_etcd', action='store_true',
考虑去掉，编程kvstore_type=‘mock'

2020-09-28 08:25 UTC, piiswrong commented on fedlearner/trainer_master/follower_tm.py
> +            data_source, db_database, db_base_dir, db_addr,
db_xxx改成一个class kvstore_config，类里面判断用什么

2020-09-28 08:26 UTC, piiswrong commented on protocols/fedlearner/common/data_join_service.proto
> +  bool use_mock_db = 1;
protobuf不能改

2020-09-28 08:26 UTC, piiswrong commented on protocols/fedlearner/common/data_portal_service.proto
> -  bool use_mock_etcd = 1;
protobuf不能改，改了就不兼容了。

2020-10-13 09:35 UTC, merged