[WebConsoleV2] Introduce authentication mechanism
bytedance/fedlearner pull request #432
Opened 2020-11-27 10:26 UTC by waynecz

* Introduce ProtectedRoute
* Give axios response mock capability

2020-11-30 04:35 UTC, waynecz commented
@island205 review request

2020-11-30 06:43 UTC, piiswrong commented
这个和后端的那个auth api连调过么？

2020-11-30 06:46 UTC, waynecz commented
> 这个和后端的那个auth api连调过么？

还没有，现在 auth 相关的接口都好了么

2020-11-30 07:55 UTC, piiswrong commented
> > 这个和后端的那个auth api连调过么？
> 
> 还没有，现在 auth 相关的接口都好了么

https://github.com/bytedance/fedlearner/blob/master/web_console_v2/api/test/test_auth.py
写了一个基础的在这里

2020-12-01 11:59 UTC, island205 commented
LGTM

2020-12-01 12:01 UTC, piiswrong requested changes

2020-12-01 12:01 UTC, piiswrong commented on web_console_v2/client/src/i18n/resources/zh_CN.ts
>  const messages = {
这里是要做统一i18n么？但是我看别的地方也有中文message？有没有i18n的framework可以用？

2020-12-01 12:03 UTC, waynecz commented on web_console_v2/client/src/typings/enum.ts
> +export enum FedRoles {
这些定义目前都是临时的，因为这部分的设计暂时还没出来

2020-12-01 12:04 UTC, waynecz commented on web_console_v2/client/src/i18n/resources/zh_CN.ts
>  const messages = {
已经有 i18n 模块了，代码里 出现 t('key') 就是多语言，login 页的文案还没定下来就先偷懒写死了

2020-12-01 12:07 UTC, waynecz commented on web_console_v2/client/src/views/Login/index.tsx
> +          <h3 className="form-title">账号登录</h3>
我去定义掉吧，后面不出现写死的文案

2020-12-01 13:14 UTC, tjulinfan commented on web_console_v2/client/src/i18n/index.ts
>    lng: 'cn', // doesn't support hyphen eg. zh-cn
现在默认语言是en还是zh?

2020-12-01 13:14 UTC, tjulinfan commented on web_console_v2/client/src/libs/mockAdapter.ts
> +    await sleep(Math.random() * 1000)
我看你很多ts里都不用分号，是现在的最佳实践嘛

2020-12-01 13:14 UTC, tjulinfan commented on web_console_v2/client/src/typings/enum.ts
>    Japanese = 'ja',
nit: ja可以去了？

2020-12-02 06:31 UTC, waynecz commented on web_console_v2/client/src/i18n/index.ts
>    lng: 'cn', // doesn't support hyphen eg. zh-cn
中文

2020-12-02 06:38 UTC, tjulinfan approved these changes

2020-12-02 09:51 UTC, merged