K8S client for add-on
bytedance/fedlearner pull request #446
Opened 2020-12-06 10:15 UTC by Abingcbc

2020-12-06 16:51 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/project/k8s_client.py
> +        except ApiException as e:
把从ApiException变成一个dict的过程封装成一个函数？

2020-12-07 03:37 UTC, piiswrong requested changes

2020-12-07 03:37 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/project/k8s_client.py
> +class K8SClient:
(object)

2020-12-07 03:37 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/project/k8s_client.py
> +# Copyright 2020 The FedLearner Authors. All Rights Reserved.
k8s_client不要放在project里，可以放在utils啥的

2020-12-07 03:37 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/project/k8s_client.py
> +            return self._build_exception_return(e)
这里为啥要这样搞？这样正确和错误的时候返回type也不一致。不在这里重试的话直接抛上去？

2020-12-07 06:03 UTC, Abingcbc commented on web_console_v2/api/fedlearner_webconsole/project/k8s_client.py
> +            return self._build_exception_return(e)
主要是不想在调用client的地方再依赖k8s的ApiException，我再封装一个K8SClientException抛出去？

2020-12-07 06:03 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/project/k8s_client.py
> +            return self._build_exception_return(e)
ApiException有K8S的detail了，我建议封装成一个咱们自己的exception，调用的地方去重试。

2020-12-07 08:02 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/project/k8s_client.py
> +            return self._build_exception_return(e)
不需要K8SClientException吧，你要考虑上游要干什么，其实只有两种，一种是瞬时错误，比如断网，那就重试，在里面自动重试也可以，另一种是参数错误，那上游也不知道怎么处理，就是返回一个错误信息给前端就行了

2020-12-07 08:04 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/utils/k8s_client.py
> +class K8SClientException(Exception):
我觉得直接把status和reason生成一个字符串，抛个rte就完了，上游拿到code也不知道怎么处理，除非再依赖k8s的error code表，那封装就没意义了

2020-12-07 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/utils/k8s_client.py
> +from kubernetes import client, config
这个依赖要写进requirements里？

2020-12-07 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/utils/k8s_client.py
> +class K8SClient(object):
K8sClient

2020-12-07 09:06 UTC, tjulinfan approved these changes

2020-12-07 09:26 UTC, merged