REST API for workflow template
bytedance/fedlearner pull request #447
Opened 2020-12-07 06:34 UTC by Ssskrilex

2020-12-07 08:00 UTC, piiswrong requested changes

2020-12-07 08:00 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +    api.add_resource(TemplateListApi, '/template')
workflow_template？

2020-12-07 08:00 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/template/models.py
> +    group_alias = db.Column(db.String(255), index=True)
这个group是干啥的

2020-12-07 08:00 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/template.proto
> +/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
protobuf层面没有template这个概念，template本身就是一个半成品workflow，用户填完就可以了

2020-12-07 08:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +    api.add_resource(TemplateListApi, '/template')
+1

2020-12-07 09:00 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/template/models.py
> +    group_alias = db.Column(db.String(255), index=True)
两侧模版做对应的，可能多对多

2020-12-07 09:05 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +            if data is None:
这种基础的校验逻辑可以用 flask自带的 argument parsing来做：
https://flask-restful.readthedocs.io/en/latest/quickstart.html#argument-parsing

2020-12-07 09:05 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +        except ParseError:
建议把try catch的范围变小一点有助于之后debug

2020-12-07 09:05 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +            db.session.commit()
可以加一条log在commit之后

2020-12-07 09:10 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/template.proto
> +/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
不如叫workflow config，这个proto主要是为了用户定义方便吧。

2020-12-07 09:16 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/template.proto
> +/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
行，那我改个名字，这个东西的名字是不是应该叫workflow好一点

2020-12-07 09:30 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/template/models.py
> +    def get_title(self):
done

2020-12-07 09:36 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/template.proto
> +/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
已经有workflow.proto了吧

2020-12-07 09:36 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +        except ParseError:
done

2020-12-07 09:47 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +            db.session.commit()
done

2020-12-07 10:23 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/template.proto
> +    //用来定义可配对模版
注释都改成英文的吧

2020-12-07 10:27 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/template.proto
> +/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
才看到你的pr，你没有merge也没喊大家review一下，就在这个pr里一起改过来吧。

2020-12-07 11:39 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +            if data is None:
done

2020-12-07 11:47 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/template.proto
> +/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
我这个就是参照你那个写的。。。

2020-12-07 14:43 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +        print(config)
print语句删掉？

2020-12-07 14:43 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +            abort(HTTPStatus.BAD_REQUEST, msg='wrong template form')
建议message直接写Invalid template

2020-12-07 14:43 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +        return {'group_alias': template.group_alias}, HTTPStatus.OK
返回整个workflow template是不是更好一点

2020-12-07 14:43 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/template/apis.py
> +            abort(HTTPStatus.BAD_REQUEST,
HTTPStatus应该是NOT_FOUND

2020-12-07 14:43 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +def initialize_template_apis(api):
把函数名改一下

2020-12-07 14:43 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +    pending_a = 1
Workflow下一个CL？

2020-12-08 03:45 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +    pending_a = 1
那我先把这半个推上去？

2020-12-08 15:40 UTC, merged