[WIP]implement job run
bytedance/fedlearner pull request #486
Opened 2020-12-30 09:57 UTC by Ssskrilex

try to implement job run and stop methods

2020-12-30 10:29 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    context = db.Column(db.Text())
直接把job definition搞进来就行了

2020-12-30 10:29 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    PRERUN = 'PRERUN'
prerun这个状态有点奇怪，要么就是ready。

2020-12-30 10:37 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/scheduler/job_scheduler.py
> +class JobScheduler(object):
线下讨论过了，不需要job scheduler，直接在scheduler里schedule workflow的时候处理一遍还没跑完的job就行了。

2021-01-04 06:47 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +def pre_run(job):
这俩放在这怎么调用？应该是放job的patch method里？

2021-01-04 06:50 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    for successor in successors:
为什么要这样链式激活？

2021-01-04 06:50 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    for successor in successors:
不需要这样，从workflow里拿到所有job，挨个stop就行了

2021-01-04 06:53 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +def pre_run(job):
本来是放job里的，但是scheduler会循环依赖。。。这俩反正也是给job restful api的run用的么

2021-01-04 06:55 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    context = db.Column(db.Text())
这样和template里的dependency一致是不是更好一点

2021-01-04 06:56 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    for successor in successors:
主要考虑到 有可能从中间的某个job开始停止重新运行

2021-01-04 06:59 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    for successor in successors:
有道理这样要锁要太多次了，我改一下放到list里一起激活吧

2021-01-04 07:26 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +def pre_run(job):
是的,但是还没想好怎么放到workflow的2pc里

2021-01-04 07:37 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    PRERUN = 'PRERUN'
done

2021-01-04 09:13 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/scheduler/job_scheduler.py
> +class JobScheduler(object):
要不先拆开 好debug一点

2021-01-04 09:13 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/scheduler/job_scheduler.py
> +class JobScheduler(object):
之后修进程bug的时候再合一下

2021-01-04 10:56 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                job = Job(name=job_definition.name+self.name,
nit: 这种不要直接这样拼接 f`{self.name}-{job_definition.name}`

2021-01-04 10:56 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/job.proto
> +  repeated JobDependency successors = 2;
为什么要存后继？

2021-01-04 10:56 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                job.set_yaml(job_definition.yaml_template)
加一个TODO：应该根据variables加上yaml_template生成yaml

2021-01-04 10:56 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job = Job.query.filter_by(name=self.target_job).first()
这里逻辑有点复杂了，其实就把workflow里面的job全都拿出来状态重置一遍，没有依赖的开始跑就行了。

2021-01-04 12:32 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +                              TransactionState.COORDINATOR_PREPARE)
这里不需要改transaction state，scheduler里会做这个

2021-01-04 12:32 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/job.proto
> +message Context {
这个是干啥用的呢？job def里面不是已经有dependency了么

2021-01-04 12:39 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +def pre_run(job):
这个不需要2pc啊，workflow处于ready状态的时候运行就行了

2021-01-05 07:30 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/job.proto
> +message Context {
想多存个后继 stop的时候好用

2021-01-05 07:30 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +                              TransactionState.COORDINATOR_PREPARE)
OK

2021-01-05 07:31 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                job.set_yaml(job_definition.yaml_template)
在set_yaml方法里有根据variables的todo

2021-01-05 07:32 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/job.proto
> +  repeated JobDependency successors = 2;
从中间节点stop的时候，有个后继好用一点

2021-01-05 07:38 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +def pre_run(job):
放到commit里了

2021-01-05 07:38 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +def pre_run(job):
啊你的意思是不是，workflow成了运行状态以后，job的运行停止是单侧行为？

2021-01-05 07:42 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job = Job.query.filter_by(name=self.target_job).first()
这么写主要是考虑从中间任务开始运行，可以复用之前的job以及workflow出现了分支只想运行单边分支的情况。

2021-01-05 07:54 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                job = Job(name=job_definition.name+self.name,
done

2021-01-05 09:10 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job = Job.query.filter_by(name=self.target_job).first()
确实 这块应该全放进去跑

2021-01-05 11:44 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/job.proto
> +message Context {
不建议这么搞，写个dag图遍历模块，按照规定条件遍历比较好

2021-01-05 11:59 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +message PatchJobResponse {
这个不需要发request的啊，双方各自调度的

2021-01-06 07:30 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        db.session.commit()
这种不应该在model里commit

2021-01-06 07:30 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +    target_job = db.Column(db.String(255), default=None)
不需要target_job吧

2021-01-06 07:30 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_scheduler.sleep(job_ids)
不需要sleep吧

2021-01-06 10:47 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    UNSPECIFIED = 'UNSPECIFIED'
done

2021-01-06 10:47 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
>  class JobStatus(enum.Enum):
done

2021-01-06 10:49 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +    target_job = db.Column(db.String(255), default=None)
done

2021-01-07 02:49 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    project = db.relationship(Project)
done

2021-01-07 02:59 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        db.session.commit()
done

2021-01-07 03:00 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/job.proto
> +  repeated JobDependency successors = 2;
ok

2021-01-07 03:20 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/job.proto
> +message Context {
ok

2021-01-07 03:23 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_scheduler.sleep(job_ids)
用sleep要个scheduler里的锁，防止又被停又被trigger，不过确实用处不大

2021-01-07 03:23 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_scheduler.sleep(job_ids)
我是想着在 对job的状态做操作的时候，暂时停掉scheduler么

2021-01-07 03:26 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +message PatchJobResponse {
中间job的运行停止这期也没安排，我先注释掉吧

2021-01-07 06:40 UTC, piiswrong requested changes

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                    job.state = JobState.READY
最好在job的orm上加个api

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                job = Job(name=f'{self.name}-{job_definition.name}',
这里不一定是创建，还有可能是重置，一个workflow可以从stopped变回ready

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_scheduler.sleep(job_ids)
如果中途被别人改了db commit会fail

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                    job.state = JobState.READY
这个逻辑没看懂，为什么不是start就改成ready

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/rpc/client.py
> +    def patch_job(self, job_names, option):
job的调度逻辑是两边各自调度，不需要操作对方的job

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +                     project_adapter.get_global_job_spec())
参考一下workflow example那个pr，v2不需要global spec了

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    def _stop(self, job):
应该不允许手工停止某个在跑的job，只能停止整个workflow。job如果是manual属性，可以手工start，前提是dependency都已经满足了

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    READY = 2
需要一个manual job处于可以被手工start的状态

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        all_successors = job.get_all_successors()
这些判定最好在workflow层面做，一次get所有job，判断每个job的状态

2021-01-07 06:40 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        return {'data': {'self': [row.to_dict() for row in
这样查询对面的频率太高了，拆分一个/jobs/job_id/peer_job的api吧

2021-01-07 09:31 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                    job.state = JobState.READY
ready(prerun)状态就是马上要跑了，只是scheduler还没trigger它。这一步是要运行所有的job，所以是要把所有的job都置成ready状态。这里如果有job是started的就说明出bug了，job的状态只有从started不能转移到ready，我报个错吧

2021-01-07 09:39 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                job = Job(name=f'{self.name}-{job_definition.name}',
重置是干嘛的，和stop操作有啥区别呢

2021-01-07 09:40 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        return {'data': {'self': [row.to_dict() for row in
OK

2021-01-07 09:42 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/client.py
> +    def patch_job(self, job_names, option):
这块我先删了吧，这个pr先不做manual的

2021-01-07 09:42 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +                     project_adapter.get_global_job_spec())
OK

2021-01-07 09:49 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    def _stop(self, job):
下个pr吧，这个我先删了

2021-01-07 09:50 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    READY = 2
下个pr再做吧

2021-01-07 09:50 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        all_successors = job.get_all_successors()
同上

2021-01-07 12:02 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                job = Job(name=f'{self.name}-{job_definition.name}',
STOPPED是不能变成RUNNING的，必须先reset成READY

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/app.py
> +    # TODO: flask will start twice, but following stop code does not work.
我这边跑了一下午没碰到这个问题，我感觉是你的配置问题。

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +class JobType(enum.Enum):
写个注释，这个地方必须和proto里的一致

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        if self.state == JobState.STARTED:
这边写个TODO吧，不应该在getter里做，这个成本很高。建议放到状态发生变化的地方做，比如说scheduler里。

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +    def get_all_successors(self):
unused function

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/client.py
> +    def patch_job(self, job_names, option):
你把这个先revert了吧

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +    def GetJobs(self, request, context):
get jobs也是，都放到其他pr里把，应该和那个workflow在一起。

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                "Workflow not in prepare state"
nit: 这里为啥改成双引号

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            sucs = {}
sucs没用了吧

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +message JobDetail{
这边也都revert了吧，感觉跟这个PR没啥关系。

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_ids = [job.id for job in
这里可以直接用`self.jobs`

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_ids = [job.id for job in
这里也可以用`self.jobs`

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                db.session.commit()
不应该在model里面commit，不然会出现一些奇怪的不在预期里的事务bug。

2021-01-07 13:25 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        for dependency in dependencies:
这种逻辑不应该放在model里了，这些都应该放在scheduler里，scheduler决定这个job能不能跑。

2021-01-07 14:08 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        if self.state == JobState.STARTED:
done

2021-01-07 14:10 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +class JobType(enum.Enum):
done

2021-01-07 14:19 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/app.py
> +    # TODO: flask will start twice, but following stop code does not work.
是有的，你控制台起的吧，把scheduler的start和stop的logging打出来，就能发现

2021-01-07 14:20 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +    def GetJobs(self, request, context):
没啥问题的话 一起交了吧

2021-01-07 14:29 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                db.session.commit()
之后把这个2pc的commit一起拆出去吧

2021-01-07 15:49 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        for dependency in dependencies:
done

2021-01-10 11:23 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        if self.state == JobState.STARTED:
那怎么保证每次拿到的job的状态都是最新的啊？
所以把get workflow和get jobs 分开可以避免太重么，要不然这样， get job 的 api是会更新的，然后get workflow的api里 也给他包上job的detail （不更新版本的）

2021-01-10 11:24 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_definitions = self.get_config().job_definitions
需要的 ，job rerun是在 started 和 stopped 之间转换和ready没关系了

2021-01-10 12:06 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        if 'peer_jobs' not in request.args:
主要我是想分开，让get jobs 是会更新 job底层状态的，重一点的操作，可以给workflow里也包上job的信息，就是不更新版本的。你看咋样，反正要有种方式让前端获得到最新的job状态

2021-01-10 12:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                db.session.commit()
那你留一个TODO吧

2021-01-10 12:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_definitions = self.get_config().job_definitions
https://github.com/bytedance/fedlearner/blob/master/web_console_v2/api/fedlearner_webconsole/workflow/models.py#L37

stopped没法直接到running啊，或者说有办法的话，那出错的时候reset到ready就会创建出重复的job了

2021-01-10 12:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        if 'peer_jobs' not in request.args:
这个没关系吧，如果说重点的操作应该是get一个job，会在job的详情页里展示出来。

2021-01-10 12:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +# must be consistent with JobState in proto
说的不是这个吧，proto里没有job state，只有job type

2021-01-10 12:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        flapp = json.dumps(self._k8s_client.get_flapp(
k8s_client里要加上这个接口。

2021-01-10 12:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        if self.state == JobState.STARTED:
一般的做法就是如果你觉得找k8s拿不是一个很耗时的做法的话，在running状态的话就直接找k8s拿，然后model里只提供读snapshot。  如果很耗时的话，就应该拿个scheduler每5秒去k8s里读一下写到job的数据库，会有一点延迟但都是可以接受的范围内。

2021-01-10 12:48 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +message JobDetail{
感觉好像都还在？

2021-01-11 05:50 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +                db.session.commit()
done

2021-01-11 05:55 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        if self.state == JobState.STARTED:
OK TODO

2021-01-11 05:58 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/models.py
> +            job_definitions = self.get_config().job_definitions
done

2021-01-11 06:27 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +        flapp = json.dumps(self._k8s_client.get_flapp(
在fake里

2021-01-11 06:28 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/models.py
> +# must be consistent with JobState in proto
done

2021-01-11 06:28 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        if 'peer_jobs' not in request.args:
拆开了

2021-01-11 06:29 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        if 'peer_jobs' not in request.args:
Done 合并了

2021-01-12 08:29 UTC, tjulinfan approved these changes

2021-01-12 08:29 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +    def GetJobs(self, request, context):
这个应该不需要了？

2021-01-12 12:46 UTC, merged