[WebConsoleV2] make workflow GET api able to get peer workflow
bytedance/fedlearner pull request #496
Opened 2021-01-06 09:51 UTC by Ssskrilex

To help users look up peer config when PUT workflow and FORK workflow, making GET api able to get peer workflows' config.

2021-01-06 11:01 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            for var in config.variables:
写一个函数filter variables，而且最好不要用 var.access_mode > common_pb2.Variable.PRIVATE 这种形式，显式地写出来哪些variable可以用。

2021-01-07 04:10 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +}
对侧job信息 在joblist的api里有，我想着这一步只负责 查看对方配置信息

2021-01-07 04:11 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        parser.add_argument('forkable', type=bool, default=False)
考虑到fork的时候么，之前讨论是fork出来的只能是false的

2021-01-07 04:39 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +                'received update_workflow_state from %s: %s',
done

2021-01-07 04:39 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/client.py
> +                logging.debug(
done

2021-01-07 04:52 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            for var in config.variables:
done

2021-01-07 06:10 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        parser.add_argument('forkable', type=bool, default=False)
为啥fork出来要是false，fork出来肯定是可以继续fork啊

2021-01-07 06:17 UTC, piiswrong requested changes

2021-01-07 06:17 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            safe_config = workflow_definition_pb2.WorkflowDefinition()
有必要创建新的么，原地filter是不是就行了

2021-01-07 06:17 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        workflow = _get_workflow(workflow_id)
不要放在这里，请求对端的频率太高了，加一个api吧/workflows/<int: workflow_id>/peer_workflows

2021-01-07 06:17 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +}
一次都返回了可能比较好，一般都是同时需要的

2021-01-07 06:19 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +}
不会有单独看对方job list的需求吧，所以直接在workflow里把workflow连带的所有job信息返回比较好。你就写个TODO吧，我到时候都merge了。

2021-01-07 10:11 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        parser.add_argument('forkable', type=bool, default=False)
之后一定是有delete概念的，如果一方想要让一个workflow删掉呢，不想再被别人fork了呢。fork的也能fork这不没完没了了。这是之前和产品讨论的，明天你们可以再讨论一下。

2021-01-07 10:36 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        workflow = _get_workflow(workflow_id)
done

2021-01-07 11:02 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +}
好的

2021-01-07 11:05 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            safe_config = workflow_definition_pb2.WorkflowDefinition()
求教这个proto的filter咋写。。

2021-01-07 11:36 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            safe_config = workflow_definition_pb2.WorkflowDefinition()
done

2021-01-07 13:02 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            self._filter_variables(config.variables)
`config.variables[:] = self._filter_variables(config.variables)`

2021-01-07 13:02 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +                job = config.job_definitions.add()
`job_def.variables[:] = self._filter_variables(job_def.variables)`

2021-01-07 13:25 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +                job = config.job_definitions.add()
done

2021-01-07 13:25 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            self._filter_variables(config.variables)
done

2021-01-07 13:26 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            variables.remove(var)
done

2021-01-07 13:36 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        parser.add_argument('forkable', type=bool, default=False)
done

2021-01-08 04:24 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +                job.CopyFrom(job_def)
你这里copyFrom了，那原本的config里的值就没有改变了啊

2021-01-08 07:42 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        if 'peer_workflow' in request.args:
不是这个意思，是说把peer workflow变成一个单独的resource

2021-01-10 04:19 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +                job.CopyFrom(job_def)
done

2021-01-10 04:20 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        if 'peer_workflow' in request.args:
done

2021-01-10 05:41 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +class PeerWorkflowApi(Resource):
PeerWorkflowsApi

2021-01-10 06:16 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +class PeerWorkflowApi(Resource):
done

2021-01-10 09:21 UTC, tjulinfan approved these changes

2021-01-10 10:51 UTC, tjulinfan approved these changes

2021-01-10 10:51 UTC, merged