bridge module dev
bytedance/fedlearner pull request #578
Opened 2021-02-04 05:41 UTC by whisylan

2021-02-04 08:16 UTC, ZhZhang711 commented on fedlearner/bridge/bridge.py
> +                raise
最后的except raise多余了，没catch住就会继续往外抛

2021-02-04 08:16 UTC, ZhZhang711 commented on fedlearner/bridge/bridge.py
> +            raise
最后的except raise多余了，没catch住就会继续往外抛

2021-02-04 08:16 UTC, ZhZhang711 commented on fedlearner/bridge/bridge.py
> +        )
duplicate code？

2021-02-04 08:16 UTC, ZhZhang711 commented on fedlearner/bridge/bridge.py
> +        first_request = next(request_iterator)
为何需要先取出一个？直接迭代会有什么问题？

2021-02-07 06:09 UTC, piiswrong requested changes

2021-02-07 06:09 UTC, piiswrong commented on fedlearner/bridge/client.py
> +        augmented_metadata = self._augment_metadata(metadata)
这个为啥要每次动态生成

2021-02-07 06:09 UTC, piiswrong commented on fedlearner/bridge/client.py
> +                logging.warn("[Bridge] grpc error, status: %s, details: %s", e.code(), e.details())
网络错误可以做一下过滤，连续出相同的错误可以少打点，避免把log都冲掉

2021-02-07 06:09 UTC, piiswrong commented on fedlearner/bridge/client.py
> +            lambda: self._client.SendStreamStream(
stream的retry是不是不应该block住当前线程

2021-02-07 06:09 UTC, piiswrong commented on fedlearner/bridge/client.py
> +            for req in request_iterator:
这里好像没看到重试队列啊，在request_iterator里面？

2021-02-09 12:24 UTC, whisylan commented on fedlearner/bridge/client.py
> +        self._channel = grpc.insecure_channel(
发送的时候带到metadata上了

2021-02-09 12:27 UTC, whisylan commented on fedlearner/bridge/client.py
> +        augmented_metadata = self._augment_metadata(metadata)
因为需要在业务的metadata里面新增，可以优化一下，如果没有metadata就用预先构建好的。但是metadata可能会变，因为一开始可能没有peer-identifity。

2021-02-09 12:28 UTC, whisylan commented on fedlearner/bridge/client.py
> +                logging.warn("[Bridge] grpc error, status: %s, details: %s", e.code(), e.details())
如果出现网络错误，wair_for_ready就会阻塞了，会进行重新连接。监听了底层的grpc channel

2021-02-09 12:31 UTC, whisylan commented on fedlearner/bridge/client.py
> +            lambda: self._client.SendStreamStream(
这个时候，还没有和对方生成stream的连接。如果不block的话，似乎还要额外的成本(线程)来维护这个状态。我再研究研究

2021-02-23 08:03 UTC, merged