multi indices
bytedance/fedlearner pull request #594
Opened 2021-02-18 06:31 UTC by ZhZhang711

multi indices to resolve ES storage overflow

2021-02-19 10:50 UTC, piiswrong commented on fedlearner/common/metrics.py
> +        if self._version == 6:
这个是干啥的

2021-02-19 11:57 UTC, piiswrong requested changes

2021-02-19 11:57 UTC, piiswrong commented on fedlearner/common/metrics.py
> +        if not self._es.indices.exists(index=index):
这个exist会不会比较慢，不需要每次都调？index变了才需要调？

2021-02-19 11:57 UTC, piiswrong commented on fedlearner/common/metrics.py
> +            for idx, actions in self._emit_batch.items():
直接用flush？而且是不是应该先flush再create新mapping

2021-02-19 11:57 UTC, piiswrong commented on fedlearner/common/metrics.py
> +        if len(self._emit_batch[index]) == 1000:
搞个环境变量吧

2021-02-19 11:57 UTC, piiswrong commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +                     'fake': int(kind == 'negative')}
为啥只改key不改kind

2021-02-20 02:27 UTC, ZhZhang711 commented on fedlearner/common/metrics.py
> +        if not self._es.indices.exists(index=index):
这个当初是预留多个index而设计的，现在只有一个index的话可以在类中保留状态来减少查询次数

2021-02-20 02:28 UTC, ZhZhang711 commented on fedlearner/common/metrics.py
> +            for idx, actions in self._emit_batch.items():
这个也是像上面那样预留多index的设计，避免flush掉其它不同类但up-to-date的index，目前的需求来看可以去掉这个设计，直接flush

2021-02-20 02:29 UTC, ZhZhang711 commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +                     'fake': int(kind == 'negative')}
因为改kind会牵扯多个文件，所以就先改了key，测试通过之后再把kind也改掉

2021-02-22 05:46 UTC, duanbing commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +        self._sample_rate = os.environ.get('JOIN_STAT_SAMPLE_RATE', 0.3)
这里怎么搞了个环境变量？

2021-02-22 05:46 UTC, duanbing commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +        self._tz = pytz.timezone('Asia/Shanghai')
这种设置是不是放到metric那个基础库里面？

2021-02-22 06:01 UTC, ZhZhang711 commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +        self._sample_rate = os.environ.get('JOIN_STAT_SAMPLE_RATE', 0.3)
junyuan说弄一个，这里的batch size对emit的性能影响挺重要的，10000条一个batch的话相比逐条emit要快100倍，不过如果这个数字太大，会导致内存增长

2021-02-22 06:01 UTC, ZhZhang711 commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +        self._tz = pytz.timezone('Asia/Shanghai')
是个好主意

2021-02-22 06:08 UTC, ZhZhang711 commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +        self._tz = pytz.timezone('Asia/Shanghai')
done

2021-02-22 06:09 UTC, ZhZhang711 commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +        self._sample_rate = os.environ.get('JOIN_STAT_SAMPLE_RATE', 0.3)
这里是因为想减少总的emit数量，目前看来数据分布正常的话采样不会对最终结果有太大影响；不过其实现在是能支持一天emit 亿级数据量，所以弄全量采样目前是没问题的

2021-02-22 08:23 UTC, piiswrong requested changes

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +              'data_join': 'data_join-{}'}
叫data_join_metrics-*?

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +INDEX_NAME = {'metrics': 'metrics_v2-{}',
会被metrics前缀匹配嘛？

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +    def emit(self, name, value, tags=None, kind='metrics'):
kind是啥？index？

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +    def emit(self, name, value, tags=None, kind='metrics'):
index_type?

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +        with self._lock:
抽个函数

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +                self._flush_index(index)
flush self._current_index[kind]

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +        with self._lock:
get_index

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +            if len(self._emit_batch[index]) >= self._batch_size:
合并成一个

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/common/metrics.py
> +atexit.register(_metrics_client.flush_handler)
放进metrics

2021-02-22 08:23 UTC, piiswrong commented on fedlearner/data_join/joiner_impl/optional_stats.py
> +        self._sample_rate = CONFIGS['join_sample_rate']
data_join_metrics_sample_rate

2021-02-22 08:36 UTC, ZhZhang711 commented on fedlearner/common/metrics.py
> +              'data_join': 'data_join-{}'}
这个现在改不了了。。dp上的名字就是data_join

2021-02-22 08:37 UTC, ZhZhang711 commented on fedlearner/common/metrics.py
> +INDEX_NAME = {'metrics': 'metrics_v2-{}',
不会，会精确匹配 - 之前的字符

2021-03-04 09:13 UTC, piiswrong requested changes

2021-03-04 09:13 UTC, piiswrong commented on fedlearner/data_join/cmd/data_portal_worker_cli.py
> -    parser.add_argument("--input_data_stat_sample_ratio",
为啥删了？

2021-03-04 09:13 UTC, piiswrong commented on requirements.txt
>  elasticsearch
默认是7么？

2021-03-04 09:44 UTC, ZhZhang711 commented on fedlearner/common/common.py
> +def convert_to_iso_format(value):
这个主要是软性要求客户用yyyymmddhhnn或者yyyymmdd格式的event time，但有些客户之前用timestamp一直没改过来，所以多了很多判断

2021-03-04 09:49 UTC, ZhZhang711 commented on fedlearner/common/common.py
> +            date_time = datetime.datetime.fromtimestamp(float(value),
因为怕event time满足长度要求但是strptime出问题，不过也可以pass掉这个except

2021-03-04 09:50 UTC, ZhZhang711 commented on fedlearner/common/metrics.py
> +        if not self._es.indices.exists_template('metrics_v2-template'):
如果其中一个没有，就认为都没有，是这个意思。不过会有put了metrics剩下两个没put上去的情况，我改改吧

2021-03-04 09:51 UTC, ZhZhang711 commented on requirements.txt
>  elasticsearch
是的，不过不知道以后8出来之后会怎么样。。我之后看看有没有版本号可以区分

2021-03-04 09:52 UTC, ZhZhang711 commented on fedlearner/data_join/cmd/data_portal_worker_cli.py
> -    parser.add_argument("--input_data_stat_sample_ratio",
因为打算和求交的sample rate放一起管理，现在放在common.py文件里了

2021-03-04 09:53 UTC, ZhZhang711 commented on deploy/scripts/data_portal/run_data_portal_worker.sh
> -input_data_stat_sample_ratio=$(normalize_env_to_args '--input_data_stat_sample_ratio' $INPUT_DATA_STAT_SAMPLE_RATIO)
放到common.py和求交的采样率一起管理了

2021-03-05 09:48 UTC, merged