Metrics plot
bytedance/fedlearner pull request #621
Opened 2021-03-01 07:18 UTC by ZhZhang711

2021-03-01 07:41 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('earliest_time', type=str, location='args',
start_time/end_time

2021-03-01 07:42 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('time_field', type=str, location='args',
xaxis_field

2021-03-01 07:43 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('field', type=str, location='args',
yaxis_field

2021-03-01 07:43 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('numerator', type=str, location='args',
yaxis_numerator

2021-03-01 07:44 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('aggregation', type=str, location='args',
aggregation_type

2021-03-01 07:44 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('aggregation', type=str, location='args',
aggregator

2021-03-01 07:45 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +                            default='auc',
不要default

2021-03-01 07:47 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('field', type=str, location='args',
value_field

2021-03-01 07:48 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('metrics', type=str, locations='args',
name

2021-03-01 07:48 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        parser.add_argument('metrics', type=str, locations='args',
metric_name

2021-03-02 07:44 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    def _get_data_join_metrics(self, job):
要不像这种大段的逻辑拆出去新弄个文件吧，这500行整进这个api太乱了

2021-03-02 07:45 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    def _get_data_join_metrics(self, job):
我那个有一个es.py query body可以放到那里

2021-03-02 07:51 UTC, ZhZhang711 commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    def _get_data_join_metrics(self, job):
然鹅KibanaMetricsApi没有用到ES...搞个新的文件？

2021-03-02 07:56 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +    def _get_data_join_metrics(self, job):
昂，搞个新文件呗。
我那个第二句话，只说下面那个query，放到es.py里封个方法呗，一致一点

2021-03-02 07:58 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        query = {
这块儿

2021-03-02 07:58 UTC, ZhZhang711 commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        query = {
这里是junyuan在弄，我看看是他来迁移还是我来迁移

2021-03-02 08:04 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        query = {
OK👌

2021-03-08 05:56 UTC, piiswrong requested changes

2021-03-08 05:56 UTC, piiswrong commented on web_console_v2/api/config.py
> +    ES_USERNAME = os.environ.get('ES_USERNAME', None)
为啥还要这个

2021-03-08 05:56 UTC, piiswrong commented on web_console_v2/api/config.py
> +    KIBANA_ADDRESS = KIBANA_HOST
这个在代码里处理就行了吧，不需要放到config里

2021-03-08 05:56 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/metrics.py
> +            overall['UNJOINED']['doc_count']]
这个不是bucket script么？不是应该是value么？

2021-03-08 05:56 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/metrics.py
> +class KibanaUtils(object):
这个放utils里吧

2021-03-08 06:22 UTC, ZhZhang711 commented on web_console_v2/api/config.py
> +    ES_USERNAME = os.environ.get('ES_USERNAME', None)
这个是zhaopeng那边买ES之后必须会有的ES账号密码

2021-03-08 06:26 UTC, ZhZhang711 commented on web_console_v2/api/fedlearner_webconsole/job/metrics.py
> +            overall['UNJOINED']['doc_count']]
现在改成根据joined的数值filter了，然后total count用bucket script计算；目前的潜在问题是如果joined以后有新type，total w/ fake的计算会不准确，可能total w/ fake改成value count

2021-03-17 03:13 UTC, piiswrong requested changes

2021-03-17 03:13 UTC, piiswrong commented on web_console_v2/Dockerfile
> +ENV TZ="Asia/Shanghai"
worker pod不加么？

2021-03-17 03:13 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/utils/es.py
> +                        "tags.joined": 1
怎么只改了这里没改worker？

2021-03-17 03:13 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/utils/es.py
> +                        "tags.joined": 1
为啥tags又回来了？

2021-03-17 03:36 UTC, merged