[WebConsoleV2] make default values not visible for user
bytedance/fedlearner pull request #627
Opened 2021-03-02 10:41 UTC by Ssskrilex

namespace, basic_envs, storage_root_dir, egress_domain, egress_host

2021-03-02 12:09 UTC, piiswrong commented
这个没必要藏起来吧

2021-03-02 12:12 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +            '{"name":"DEFAULT_BASIC_ENVS", "value":""}'
为啥要搞个这个

2021-03-02 12:21 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +            '{"name":"DEFAULT_BASIC_ENVS", "value":""}'
每个template 不都要用这个 project.basic_envs，没这个format的时候报错呢，需要个占位置的默认值，而这个默认值是个没啥用的值，就放到这藏起来了。
主要想藏的是那个egress_domain和 egress_host。这俩东西和证书以及那个domain name 必须一致，也不是能改和需要改的，所以就藏在这了，（主要发现这俩东西太容易填错了）
至于其他的project的variables，就让用户自己填去，然后我想着加个 project.variables和template里面依赖的一致性校验。但是不知道放哪好一点，是post workflow的时候呢还是run的时候，目前想的是放在run的那块儿，有啥建议吗？
（又或者显示的在界面上提示一下workflow使用的模版需要 project 有哪些varibles？）

2021-03-02 12:21 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +            '{"name":"DEFAULT_BASIC_ENVS", "value":""}'
每个template 不都要用这个 project.basic_envs，没这个format的时候报错呢，需要个占位置的默认值，而这个默认值是个没啥用的值，就放到这藏起来了。
主要想藏的是那个egress_domain和 egress_host。这俩东西和证书以及那个domain name 必须一致，也不是能改和需要改的，所以就藏在这了，（主要发现这俩东西太容易填错了）
至于其他的project的variables，就让用户自己填去，然后我想着加个 project.variables和template里面依赖的一致性校验。但是不知道放哪好一点，是post workflow的时候呢还是run的时候，目前想的是放在run的那块儿，有啥建议吗？
（又或者显示的在界面上提示一下workflow使用的模版需要 project 有哪些varibles？）

2021-03-02 12:22 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +            '{"name":"DEFAULT_BASIC_ENVS", "value":""}'
每个template 不都要用这个 project.basic_envs，没这个format的时候报错呢，需要个占位置的默认值，而这个默认值是个没啥用的值，就放到这藏起来了。
主要想藏的是那个egress_domain和 egress_host。这俩东西和证书以及那个domain name 必须一致，也不是能改和需要改的，所以就藏在这了，（主要发现这俩东西太容易填错了）
至于其他的project的variables，就让用户自己填去，然后我想着加个 project.variables和template里面依赖的一致性校验。但是不知道放哪好一点，是post workflow的时候呢还是run的时候，目前想的是放在run的那块儿，有啥建议吗？
（又或者显示的在界面上提示一下workflow使用的模版需要 project 有哪些varibles？）

2021-03-02 12:23 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +            '{"name":"DEFAULT_BASIC_ENVS", "value":""}'
每个template 不都要用这个 project.basic_envs，没这个format的时候报错呢，需要个占位置的默认值，而这个默认值是个没啥用的值，就放到这藏起来了。
主要想藏的是那个egress_domain和 egress_host。这俩东西和证书以及那个domain name 必须一致，也不是能改和需要改的，所以就藏在这了，（主要发现这俩东西太容易填错了）
至于其他的project的variables，就让用户自己填去，然后我想着加个 project.variables和template里面依赖的一致性校验。但是不知道放哪好一点，是post workflow的时候呢还是run的时候，目前写的是放在run的那块儿，有啥建议吗？
（又或者显示的在界面上提示一下workflow使用的模版需要 project 有哪些varibles？）

2021-03-03 14:45 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +            '{"name":"DEFAULT_BASIC_ENVS", "value":""}'
这个basic_envs现在不需要了，因为里面的东西大部分都从`get_system_envs`里有了

2021-03-03 14:45 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +    if 'storage_root_dir' not in project['variables']:
我建议这几个校验就不用加了，假设project的variable必须填，如果这几个是必须的，咱们就在前端hard code一下，然后后端API做个校验（在创建project的时候）。自动帮用户生成这里感觉不是很可靠

2021-03-08 05:46 UTC, piiswrong requested changes

2021-03-08 05:46 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        workflow.transaction_state = TransactionState.PARTICIPANT_COMMITTABLE
这个不能直接这么改吧，啥都没check，还是应该让workflow model自己改，这里是不是wakeup一下就行了

2021-03-08 05:46 UTC, piiswrong commented on web_console_v2/api/test/fedlearner_webconsole/workflow_template/test_template_left.py
> +                                        "value": "${project.participants.egress_host}"
这个为啥在participants里？不是应该分[0],[1]这样么

2021-03-09 08:42 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +        workflow.transaction_state = TransactionState.PARTICIPANT_COMMITTABLE
确实，debug忘改了。。。

2021-03-10 08:29 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow/apis.py
> +                            uuid=f'u{uuid4().hex[:19]}',
这样还能保证唯一吗？可以考虑在uuid前面加个前缀

2021-03-10 08:29 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/yaml_formatter.py
> +def job_run_yaml(job):
nit: 函数名最好是动词比如 `generate_job_run_yaml`

2021-03-10 08:29 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +        for job_def in template_proto.job_definitions:
nit: 这里也可以用 `enumerate`

2021-03-11 05:42 UTC, tjulinfan approved these changes

2021-03-11 05:43 UTC, merged