[WebconsoleV2] job get events
bytedance/fedlearner pull request #651
Opened 2021-03-08 11:59 UTC by Ssskrilex

2021-03-09 06:07 UTC, piiswrong requested changes

2021-03-09 06:07 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            job = Job.query.filter_by(name=request.job_name).first()
这里要限制project id

2021-03-09 06:07 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
> +            job = Job.query.filter_by(name=request.job_name).first
限制project

2021-03-09 09:26 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +                     '/peer_jobs/<int:participant_id>/<int:job_id>/events')
这个有点奇怪，因为不同job的participant是不一样的搞成job_id/participants/participants_id?

2021-03-09 09:28 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +message GetJobEventsRequest {
events我觉得还是workflow带过来比较好，这样请求次数少点？metrics分开主要是因为计算量和数据量都比较大，需要用户主动获取，events应该是默认获取的

2021-03-09 09:31 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +message GetJobEventsRequest {
events是从es里查的是吧？那可能还是有点重

2021-03-09 10:46 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
> +message GetJobEventsRequest {
是的，从es里查的而且量不小。。。

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        job = Job.query.get(job_id)
check一下job可能不存在

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        job = Job.query.get(job_id)
这里一样的

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        job = Job.query.get(job_id)
也要check

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        resp = client.get_job_metrics(workflow.name, job.name)
这个函数不需要workflow name了吧

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +                            help='project_id must be timestamp')
help message有问题

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        job = Job.query.get(job_id)
记得check job

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        job = Job.query.get(job_id)
check

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +class JobEventApi(Resource):
写测试

2021-03-10 08:46 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/rpc/server.py
>              return service_pb2.GetJobMetricsResponse(
这个类型错了？

2021-03-11 05:40 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/job/apis.py
> +        job = Job.query.get(job_id)
这里还是没有改啊

2021-03-11 05:43 UTC, tjulinfan approved these changes

2021-03-11 06:16 UTC, tjulinfan approved these changes

2021-03-11 06:16 UTC, merged