[WebConsoleV2] add code_key encoding and decoding
bytedance/fedlearner pull request #669
Opened 2021-03-12 12:17 UTC by Ssskrilex

2021-03-14 03:33 UTC, piiswrong requested changes

2021-03-14 03:33 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +            return f'code://{result}'
叫base64://?

2021-03-14 03:33 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +                        if variable['name'] in CODE_KEYS:
这里是hardcode了variable name么？考虑改成按schema type来？前端现在是有type的吧

2021-03-14 03:33 UTC, piiswrong commented
要确认一下旧版的code key仍然能支持

2021-03-14 04:30 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +            return f'code://{result}'
和前端讨论了一下，感觉还是把旧的 code_key 的参数和这个codes参数分开吧

2021-03-14 04:33 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +                        if variable['name'] in CODE_KEYS:
好主意

2021-03-14 04:43 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +CODES = ['codes', 'CODES']
改成CODE_TAR?要么干脆用schema type判断，不要hardcode名字

2021-03-14 07:32 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +CODES = ['codes', 'CODES']
OK

2021-03-14 07:52 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +            return f'code://{result}'
我傻了，仔细想了一下，这个variable层面分开就行了，环境变量好像还是只能有一个

2021-03-14 13:38 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +        raise InvalidArgumentException('The value of a code type Variable '
这个地方建议不要在parser throw invalid argument exception，因为你并不知道谁会调用你。其实这里在函数开头的时候assert一下就行了，然后在调用前保证这个输入是正确的。
```
def _encode(self, data_dict):
  assert isinstance(data_dict, dict)
```

2021-03-14 13:38 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +        raise InvalidArgumentException('The stored value of a code type '
这里也一样

2021-03-14 13:38 UTC, tjulinfan commented on web_console_v2/api/test/fedlearner_webconsole/utils/code_key_parser_test.py
> +        data = test_data
这个赋值是什么意义

2021-03-14 13:38 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +                    variable['value'] = self._decode(variable['value'])
这里为啥要decode code_key?

2021-03-14 13:38 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/common.proto
> +  enum ValueType{
nit: enum ValueType { (记得空格）

2021-03-14 13:38 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +    def encode_code_key_in_config(self, config):
如果是在后端encode和decode，为啥不在拼yaml的时候encode? 然后数据库里存明文就好了，base64反而更消耗空间。

```
message Variable {
  enum AccessMode {
    UNSPECIFIED = 0;
    PRIVATE = 1;
    PEER_READABLE = 2;
    PEER_WRITABLE = 3;
  }

  enum ValueType {
    STRING = 0;
    CODE = 1;
  }
  string name = 1;
  oneof value_oneof {
      string value = 2;
      // key: path, value: file-content
      map<string, string> code = 6;
  }
  AccessMode access_mode = 3;
  string widget_schema = 4;
  ValueType value_type = 5;
}
```

2021-03-15 08:47 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +    def encode_code_key_in_config(self, config):
如听仙乐耳暂明！！！！！

2021-03-16 06:17 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +            with open(code_path, 'rb') as file:
这里没看懂，为啥从文件里读？不是从variable protobuf里读吗？

2021-03-16 06:18 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +            with open(code_path, 'rb') as file:
意思是code key也能编辑？那还要写回去？好像有点奇怪

2021-03-16 06:19 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +        print(str(e))
用logging？

2021-03-16 06:39 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +            with open(code_path, 'rb') as file:
意思是给webcode ide 整个load from的功能嘛，不写回去

2021-03-16 12:00 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +    api.add_resource(CodeApi, '/code_key')
这个路径感觉有点奇怪 建议是`/codes`

然后 `GET /codes?code_path=xxx` 去读取tar包的代码

2021-03-16 12:00 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +                data_string = str(base64.b64encode(file.read()),
没懂这里为啥还要encode？不应该直接是tar包吗？

2021-03-16 12:00 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
>          template_proto = ParseDict(config,
parse完了校验感觉更简单一点？

2021-03-16 12:00 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +                config['variables'][index] = _classify_variable(variable)
为什么需要重新赋值？

2021-03-16 12:00 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/utils/code_key_parser.py
> +    def encode(self, data_dict):
感觉不需要encode和decode了？只要在拼yaml的时候encode就好了？  数据库里存json string

2021-03-17 02:58 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +            with open(code_path, 'rb') as file:
ok

2021-03-17 06:02 UTC, merged