Fix Nginx DNS error log
bytedance/fedlearner pull request #676
Opened 2021-03-15 05:37 UTC by Abingcbc

Reference:
https://github.com/coredns/coredns/issues/2324
https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

2021-03-15 06:29 UTC, tjulinfan commented
LGTM

2021-03-17 02:12 UTC, tjulinfan requested changes

2021-03-17 02:12 UTC, tjulinfan commented on deploy/charts/fedlearner-add-on/templates/service.yaml
> +      - ip: {{ .Values.service.externalName }}
如果是域名怎么办？

2021-03-17 06:19 UTC, Abingcbc commented on deploy/charts/fedlearner-add-on/templates/service.yaml
> +      - ip: {{ .Values.service.externalName }}
域名好像创建就会失败了

2021-03-17 06:19 UTC, closed without merging