pack_grad_hess
bytedance/fedlearner pull request #726
Opened 2021-03-25 03:16 UTC by hangweiqiang-uestc

Pack Grad and Hess

https://bytedance.feishu.cn/docs/doccnXYZkb4e0pugEAsI1KqAEzb#

2021-03-25 13:41 UTC, tjulinfan requested changes

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/packing.py
> +        enc_numbers = [
这种是不是让需要的地方生成就好了？

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/packing.py
> +class PackGradHess:
nit: class名字最好叫名词吧，比如GradHessPacker或者GradHessEncryptor之类的

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/packing.py
> +        Grad Hess Pack
注释这些再整理一下吧

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/packing.py
> +        grad_plaintext = [(plaintext >> self.offset) % self._n
mod _n还需要吗？

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/packing.py
> +        cipher_sum = ciphertexts[0] % nsquare
建议assert一下ciphertexts size大于0

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/packing.py
> +    def raw_add(self, ciphertexts, nsquare=None):
建议直接用public_key里的nsquare更自洽一点，这里设置这个参数是有什么考量吗？

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/tree.py
> +def _encrypt_and_send_numbers_by_id(args):
函数名改一下(没有在这里面send)

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/tree.py
> +    public_key, part, i = args
nit: 感觉取点有意义的名字？比如 public_key, numbers, part_index

2021-03-25 13:41 UTC, tjulinfan commented on fedlearner/model/tree/tree.py
> +            bridge.send_proto(bridge.current_iter_id, '%s_part_%d' % (name, i),
这里还是得线性发送是吧，原因是因为开了进程所以不能在进程里搞吗？

2021-03-26 02:52 UTC, hangweiqiang-uestc commented on fedlearner/model/tree/packing.py
> +    def raw_add(self, ciphertexts, nsquare=None):
我也忘了当时为啥设置这个参数了，不过这个函数我整个去掉了，一开始是为了做测试加的

2021-03-26 02:53 UTC, hangweiqiang-uestc commented on fedlearner/model/tree/tree.py
> +            bridge.send_proto(bridge.current_iter_id, '%s_part_%d' % (name, i),
后台有个锁，不过线性发送效率应该差不多？

2021-03-26 04:06 UTC, hangweiqiang-uestc reviewed
用了一下yapf，没想到改了那么多代码。。。。

2021-03-26 05:09 UTC, duanbing commented on fedlearner/model/tree/packing.py
> +    def __init__(self, public_key, private_key, precision, exponent):
这里pk和sk能不能作为pack or unpack的参数？让人误以为pack也需要私钥等

2021-03-26 05:18 UTC, duanbing commented on fedlearner/model/tree/packing.py
> +        bit_length = self.offset - 48
48是怎么来的？

2021-03-26 05:20 UTC, duanbing commented on test/tree_model/test_pack.py
> +        grad = [random.randint(-1e100, 1e100) for i in range(1000)]
增加下下packing溢出的test case?

2021-03-26 07:00 UTC, hangweiqiang-uestc commented on fedlearner/model/tree/packing.py
> +        bit_length = self.offset - 48
这个48是为了防止多个负数相加导致结果溢出，从hess的位置溢出到grad的位置。现在只有2^48个数相加才有可能发生前面说的那种溢出。2^48差不多万亿规模了，实际中应该不会发生。

2021-03-26 07:02 UTC, hangweiqiang-uestc commented on test/tree_model/test_pack.py
> +        grad = [random.randint(-1e100, 1e100) for i in range(1000)]
这个大概是个啥样的？
溢出不就出错了吗？

2021-03-26 07:05 UTC, hangweiqiang-uestc commented on fedlearner/model/tree/packing.py
> +    def __init__(self, public_key, private_key, precision, exponent):
可以把private_key作为decrypt_and_unpack_grad_hess那个函数的参数。

2021-03-26 07:07 UTC, hangweiqiang-uestc commented on fedlearner/model/tree/packing.py
> +        grad_plaintext = [(plaintext >> self.offset) % self._n
需要的，有可能会出现decrypt([[-1]]*[[1]]%nsquare)等于n的情况。

2021-03-28 10:30 UTC, duanbing commented
@piiswrong 你也看下吧。 我这边没啥问题了。

2021-03-28 11:22 UTC, piiswrong approved these changes

2021-03-29 06:04 UTC, tjulinfan approved these changes

2021-03-29 07:10 UTC, merged