[WebConsoleV2] add Slots format for workflow template
bytedance/fedlearner pull request #737
Opened 2021-03-28 03:18 UTC by Ssskrilex

2021-03-28 03:43 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +message Slot {
为啥还需要个proto？这个是干啥的？

2021-03-28 07:13 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +message Slot {
整简易模式，和waynecz 讨论了下，准备每个job写一份基本模版，然后slot是每个单元插槽。简易模式就前端只用修改slot就行了。然后前端可以按slot编辑 或者把slot按对应variable group一哈编辑。

2021-03-28 07:17 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +        DEFAULT = 0;
就是不抽variable了，直接用default里的值

2021-03-29 03:46 UTC, piiswrong requested changes

2021-03-29 03:46 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +        job_def.yaml_template = generate_yaml_template(job_def.yaml_template,
为什么会出现这种情况？

2021-03-29 03:46 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/slots_formatter.py
> +class _YamlTemplate(Template):
加点空行

2021-03-29 03:46 UTC, piiswrong commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +    map<string, Slot> slots = 7;
删了？

2021-03-29 03:46 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +        job_def.yaml_template = generate_yaml_template(job_def.yaml_template,
这个事情不是应该在前端干了吗？job_def.yaml_template不应该是个meta yaml

2021-03-29 03:46 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/slots_formatter.py
> +def generate_yaml_template(base_yaml, slots_proto):
这个事情应该在前端提交的时候就干了吧

2021-03-29 03:46 UTC, piiswrong commented on web_console_v2/api/fedlearner_webconsole/workflow_template/slots_formatter.py
> +def generate_yaml_template(base_yaml, slots_proto):
要不就单独提供一个api，放在workflow template下面

2021-03-29 04:18 UTC, closed without merging