[WIP][WebConsoleV2] add Slots format for workflow template method2
bytedance/fedlearner pull request #741
Opened 2021-03-28 12:51 UTC by Ssskrilex

2021-03-29 13:48 UTC, tjulinfan requested changes

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +    string label = 5;
这个label是干啥的？

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +    map<string, Slot> slots = 1;
这里slots的key给个example

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/models.py
> +
nit: 把多余的空行去掉

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/models.py
> +    editor_info = db.Column(db.LargeBinary(16777215),
更新migration

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/models.py
> +                       'editor_info':
这个也有点大吧，是不是得走download那个API

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +        yaml_editor_infos = editor_info_proto.yaml_editor_infos
这个不适合在这个函数里干吧，新开一个函数好了。

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
>          return {'data': [_dic_without_key(t.to_dict(),
干脆把这两个大的field从to_dict里拿掉好了，看起来前端并不是很关心，可以和前端再double check一下

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/slots_formatter.py
> +        self, *args = args  # allow the "self" keyword be passed
为啥不直接写`def substitute(self, *args, **kwargs)`
好像Template自己就是这样写的：https://github.com/python/cpython/blob/master/Lib/string.py#L104

2021-03-29 13:48 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/slots_formatter.py
> +        if not args:
你只有自己用，感觉可以简化一下？只考虑传入dict的情况好了

2021-03-29 14:14 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +    string label = 5;
标注它是干嘛的？

2021-03-29 15:19 UTC, Ssskrilex commented on web_console_v2/api/fedlearner_webconsole/workflow_template/models.py
> +                       'editor_info':
走download 那个是因为，前端没法做下载嘛，get没啥问题吧

2021-03-30 03:57 UTC, tjulinfan requested changes

2021-03-30 03:57 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +    string label = 5;
那和help的区别是啥

2021-03-30 03:57 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +    editor_info_proto = dict_to_editor_info(editor_info)
这个也没必要在这个函数里面吧

2021-03-30 03:57 UTC, tjulinfan commented on web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
> +    return template_proto
return editor的proto就行了

2021-03-30 10:14 UTC, Ssskrilex commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +    string label = 5;
不知道。。前端需要好像

2021-03-31 04:31 UTC, tjulinfan approved these changes

2021-03-31 04:32 UTC, tjulinfan commented on web_console_v2/api/protocols/fedlearner_webconsole/proto/workflow_definition.proto
> +    string label = 5;
label是用来前端显式UI的 help是tooltip里的内容。

2021-03-31 04:32 UTC, merged