verify enable_packing
bytedance/fedlearner pull request #748
Opened 2021-03-29 15:16 UTC by hangweiqiang-uestc

add enable_packing in verify parameters in tree.

2021-03-30 03:38 UTC, tjulinfan requested changes

2021-03-30 03:38 UTC, tjulinfan commented on fedlearner/model/tree/packing.py
> +class GradHessPacker:
这个好像已经在repo里了？

2021-04-06 05:27 UTC, hangweiqiang-uestc commented on fedlearner/model/tree/tree.py
> +        for hist in hists:
那个Pool返回的是个iterator，貌似只能for循环走一次。第二次就是个空的。

2021-04-06 05:36 UTC, duanbing commented on fedlearner/model/tree/tree.py
> +        for hist in hists:
👍

2021-04-06 05:36 UTC, duanbing approved these changes

2021-04-06 05:37 UTC, duanbing commented
@piiswrong  你看下？ 修复之前imap异常的问题。

2021-04-06 15:28 UTC, tjulinfan approved these changes

2021-04-07 11:52 UTC, merged