Trainer v1.2
bytedance/fedlearner pull request #799
Opened 2021-04-19 10:44 UTC by whisylan

2021-04-19 12:12 UTC, piiswrong commented on deploy/scripts/trainer/run_trainer_master.sh
> +sparse_estimator=$(normalize_env_to_args "--sparse-estimator" "$SPARSE_ESTIMATOR")
这个挪位置的话2.0需要改ticket

2021-04-19 12:14 UTC, piiswrong commented on fedlearner/trainer/estimator.py
> +            with tf.train.MonitoredSession(
不用training session了么？

2021-05-11 12:27 UTC, piiswrong requested changes

2021-05-11 12:27 UTC, piiswrong commented on fedlearner/trainer/data_visitor.py
> +class _RowDataBlock(
Raw？

2021-05-11 12:27 UTC, piiswrong commented on fedlearner/trainer/data_visitor.py
> +            data = self._try_parse_v1(buff)
这个为啥还有v1和v2

2021-05-11 12:27 UTC, piiswrong commented on fedlearner/trainer/estimator.py
> -        with tf.control_dependencies([self._example_ids]):
这个为啥去了

2021-05-11 12:27 UTC, piiswrong commented on fedlearner/trainer/sparse_estimator.py
> +                 feature_columns=None):
这是干啥的

2021-05-11 12:27 UTC, piiswrong commented on fedlearner/trainer/sparse_estimator.py
> +            ps_indices = cluster_server.cluster_spec.task_indices('ps')
这为啥要try，不能直接看has field啥的么

2021-05-11 12:27 UTC, piiswrong commented on fedlearner/trainer/trainer_master.py
> +            logging.info("skip save checkpoint")
让master来做的话这里是不是就不需要skip了？

2021-05-11 12:27 UTC, piiswrong commented on fedlearner/trainer/trainer_master.py
> +class DataBlockCheckpointSaverListener(tf.train.CheckpointSaverListener):
为啥要有DataBlockCheckpointSaverListener， _DataVisitorCheckpointHook，CheckpointSaverListener三个？

2021-05-12 12:25 UTC, duanbing commented on fedlearner/common/logging.py
> +_logger = _create_logger()
https://github.com/bytedance/fedlearner/blob/master/fedlearner/common/common.py#L252    跟这个统一下吧

2021-05-12 13:05 UTC, duanbing commented on fedlearner/trainer/data_visitor.py
> +            data = self._try_parse_v1(buff)
改了data checkpoint的tensor name了

2021-05-12 13:18 UTC, duanbing commented on fedlearner/trainer/trainer_master_client.py
> +        while True:
这里rpc with try了， 为什么还要while True呢？

2021-05-18 07:16 UTC, piiswrong requested changes

2021-05-18 07:16 UTC, piiswrong commented on fedlearner/trainer/trainer_master.py
> +                    tf.train.CheckpointSaverHook(
checkpoint还是tf的逻辑写的是吧，还没做管理？

2021-05-25 08:33 UTC, merged